/*
 * LearnChess logo: the Instrumenta brand v2 rook, a freestanding drawing with
 * depth and no tile behind it. Drawn by `public/brand/instrumenta-icons.js`
 * (copied from the Instrumenta brand folder, see docs/brand/README.md) and
 * loaded as a classic script in index.html, so it exposes
 * `window.InstrumentaIcons`.
 *
 * The rook rests, and hops while an ancestor has `ii-play`, or while an
 * `ii-hover` ancestor is hovered or focused (see instrumenta-icons.css, which
 * also stops all motion under prefers-reduced-motion). The markup uses
 * presentation attributes only, so it is safe under a strict
 * Content-Security-Policy.
 *
 * If the script is missing (it should never be), the static brand SVG is used.
 *
 * Sizing: pass `size` in CSS px; the viewBox is fixed and scales with it.
 */
interface InstrumentaIconsApi {
  render(id: string, options?: { size?: number; label?: string }): string;
}

declare global {
  interface Window {
    InstrumentaIcons?: InstrumentaIconsApi;
  }
}

interface LogoProps {
  size?: number;
  className?: string;
  'aria-label'?: string;
  /** Render decorative-only? Defaults to false (uses role="img"). */
  decorative?: boolean;
}

export function Logo({
  size = 28,
  className,
  'aria-label': ariaLabel = 'LearnChess',
  decorative = false,
}: LogoProps) {
  const icons = typeof window === 'undefined' ? undefined : window.InstrumentaIcons;
  if (!icons) {
    return (
      <img
        src="/brand/learnchess.svg"
        width={size}
        height={size}
        alt={decorative ? '' : ariaLabel}
        className={className}
      />
    );
  }
  const markup = icons.render('learnchess', { size, label: decorative ? '' : ariaLabel });
  return (
    <span
      className={`inline-flex ${className ?? ''}`}
      // The markup is generated by our own vendored icon library from constants.
      dangerouslySetInnerHTML={{ __html: markup }}
    />
  );
}
